### PR TITLE
really fix lightmap issues

### PR DESCRIPTION
**Pull request by sezero**
As noted at https://github.com/Shpoike/Quakespasm/commit/5cbb199b5cf5aece009be92c0a9b8bacf33c7546#comments, lightmaps are still broken (see attached screenshot.)
Fix picked from https://github.com/sezero/quakespasm/commit/94db75126c4891c36a9e373f312a795cc9847f1f

e2m1

### CODE REVIEW

**Comment by adelpha** [comment]
Does this also fix the issue with entities appearing black in certain places in DoTM? Video below:

https://youtu.be/lrmQSEon24k

**Comment by sezero** [comment]
> Does this also fix the issue with entities appearing black in certain places in DoTM?

Honestly don't know - and won't try it myself.

**Comment by garoto** [comment]
> Does this also fix the issue with entities appearing black in certain places in DoTM? Video below:

Applied sezero's patch ontop of the `qsrebase` branch and nope:

spasm0001

**Comment by adelpha** [comment]
I'll open a new issue for this, rather than cluttering this perfectly good PR any more.

**Comment by sezero** [comment]
Looks like this has been fixed by merging mainstream changes.

**Pull request closed without merging**
